### ISSUE TITLE
ppcomp fails to parse html file

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/ppwb#12]
The [attached html and text files](https://github.com/DistributedProofreaders/ppwb/files/5791841/lettersfromandoldtimesalesman.zip) cause the following error log:
```
Traceback (most recent call last): File "./bin/comp_pp.py", line 1621, in main() File "./bin/comp_pp.py", line 1616, in main _, html_content, fn1, fn2 = x.do_process() File "./bin/comp_pp.py", line 1338, in do_process f.load(fname) File "./bin/comp_pp.py", line 694, in load self.myfile.load_xhtml(filename, relax=True) File "./bin/comp_pp.py", line 223, in load_xhtml os.path.basename(name)) SyntaxError: Parsing errors in document: lettersfromandoldtimesalesman.html
```
The HTML file validates OK at W3C.

**Comment by asylumcs** [comment]
The error is caused by lines 146, 150 and 156 in the source file. The file has "<hr></hr>" instead of "<hr/>" and that causes the XML parser to fail. At this point I only know why it fails. I don't know yet (1) how a user could detect that situation easily, or (2) what could be changed in ppcomp to either identify it or live with it.

**Comment by windymilla** [comment]
Thanks. I hadn't spotted them.

**Comment by asylumcs** [comment]
If we don't want to consider those an error--and the HTML validator apparently says it's okay--then we should change the code to accept it. For that to happen, I believe it's as simple as putting this in the "cleanup some errors" block near line 220 of comp_pp.py:
`self.parser_errlog = [x for x in parser.error_log if parser.error_log[0].type != 76]`
I can start a PR for that if we want to ignore it and continue in ppcomp. Or maybe we want ppcomp to flag it and continue. Or maybe just flag it and bail out. What do we want to happen?

**Comment by windymilla** [comment]
I would be happy with flag and continue or flag and fail.

**Comment by rtonsing** [comment]
It may pass W3C, but it does not pass Nu Html checker:
Error: Stray end tag hr.
From line 2904, column 5; to line 2904, column 9
</p>↩↩<hr></hr>↩↩<p c

and according to the Whatwg.org standard is not valid html.
