### ISSUE TITLE
Minor update to ppcomp web page

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/ppwb#21]
The option `Type of text cleaning:` can be removed, there is no code to support it.

I'm working on a major upgrade to ppcomp to handle HTML5 & other changes, and noticed this.

**Comment by cpeel** [comment]
Sorry, what `ppcomp web page` are you referring to?

**Comment by cpeel** [comment]
The `txt-cleanup-type` form value gets passed into `comp_pp.py` as `--txt-cleanup-type` which is used in `comp_pp.py` in [pgdp_file_text.convert()](https://github.com/DistributedProofreaders/ppwb/blob/master/bin/comp_pp.py#L539). So it appears to do something.

**Comment by rtonsing** [comment]
Apparently a version difference.

**Comment by cpeel** [comment]
Yes, unfortunately there are multiple different copies of the code floating around.
